packages:
  - .

allowBuilds:
  "@embedded-postgres/windows-x64": true
  "@embedded-postgres/linux-x64": true
  "@embedded-postgres/linux-arm64": true
  "@embedded-postgres/darwin-x64": true
  "@embedded-postgres/darwin-arm64": true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
